// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/DataProviderGE","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/promise/all esri/dijit/geoenrichment/when esri/kernel ./dataProvider/_CommandSupport ./dataProvider/_SerializationSupport ./dataProvider/_ServerSerializationSupport ./dataProvider/supportClasses/areas/AnalysisAreaUtil ./dataProvider/supportClasses/areas/AnalysisAreaJsonUtil ./dataProvider/supportClasses/areas/AreasPreprocessor ./dataProvider/supportClasses/CustomReportsManager ./dataProvider/supportClasses/TemplateJsonLoader ./dataProvider/supportClasses/ReportDataProcessor ./dataProvider/supportClasses/GEUtil ./dataProvider/supportClasses/attachments/DefaultAttachmentsStore ./dataProvider/supportClasses/attachments/CustomAttachmentsStore ./dataProvider/supportClasses/data/VariablesUtil ./dataProvider/commands/mapToImage/MapToURLUtil ./core/themes/ThemeLibrary ./core/themes/ReportThemes esri/dijit/geoenrichment/ReportPlayer/config esri/dijit/geoenrichment/ReportPlayer/countryConfig esri/dijit/geoenrichment/utils/ProjectionUtil esri/dijit/geoenrichment/utils/PortalUtil esri/dijit/geoenrichment/utils/UrlUtil".split(" "),
function(C,m,u,n,D,E,F,G,v,w,x,p,y,t,q,H,I,J,K,L,z,M,k,N,O,A){return C([E,F,G],{analysisAreasLimit:-1,cacheTemplates:!0,printMapTaskUrl:null,resetReportItemsCache:!0,constructor:function(b){m.mixin(this,b)},_getAttachmentsStore:function(b){return(new H(b)).initialize()},_currentContext:null,getReportData:function(b,e){var d=this,f=e&&e.progressCallback||function(){},a=m.mixin({},b);a.portalUrl=A.getPortalUrl(a.portalUrl);M.isPlayerOnServer||A.setArcgisUrl(a.portalUrl);v.parseSites(a);k.reset();a.hierarchy||
a.analysisAreas.some(function(c){if(c.geographies&&c.geographies[0].hierarchy)return a.hierarchy=c.geographies[0].hierarchy,!0});d.resetReportItemsCache&&p.resetCache();d._currentContext=a;a.analysisAreas=w.areasFromJson(a.analysisAreas);a.combinedAreasInfo=a.combinedAreasInfo&&w.combinedAreasInfoFromJson(a.combinedAreasInfo)||{};v.populateCombinedAreasInfo(a.combinedAreasInfo,a.analysisAreas);a.fieldData={specialTradeAreaCalculatorName:null,runReportTaskIDs:null,metadata:{},areaData:[],errors:[],
reportInfo:null};return u([n(p.tryFindReportIdByAlias(a),function(c){a.reportID=c||a.reportID}),this._discoverPortal(a),function(){return a.variables&&n(J.preprocessVariables(a.variables,a.portalUrl),function(c){a.variables=c})}()]).then(function(){return n(x.preprocessAreas(a,{analysisAreasLimit:d.analysisAreasLimit}),function(){f(.25);setTimeout(function(){d._onCreateReportStarted()});var c=a.attachmentsProvider?I(a.attachmentsProvider):d._getAttachmentsStore(a.analysisAreas),g={initGE:q.initialize(),
countryInfo:q.getCountryInfo(a.countryID),attachmentsStore:c};a.reportID?(g.reportObject=p.getCustomReportByID(a),g.templateJsonInfo=y.getTemplateJsonByID(a,d.cacheTemplates),g.runReportResult=t.runReportAndGetData(a,c)):a.variables&&(g.reportObject=p.getFakeCustomReportByContext(a),g.templateJsonInfo=y.createTemplateJsonFromVariables(a),g.runReportResult=t.runReportFromVariables(a));return u(g).then(function(h){var l=h.reportObject,P=h.attachmentsStore,r=h.templateJsonInfo.templateJson,Q=h.templateJsonInfo.templateVariableProvider,
R=h.runReportResult;f(.75);if(!r||!l||!a.fieldData)return null;k.setCountry(h.countryInfo.country);k.setHierarchyID(a.hierarchy);k.setGeographiesModel(h.countryInfo.geographiesModels[k.getHierarchyID()]);r.theme||(r.theme=L.getReportThemeById(l.isGraphicReport?z.GRAPHIC:z.CLASSIC));var B={isMultiFeature:l.isMultiFeature&&1<a.analysisAreas.length,reportTitle:a.reportTitle||l.title,templateJson:r,reportObject:l,fieldData:a.fieldData,analysisAreas:a.analysisAreas,combinedAreasInfo:a.combinedAreasInfo,
reverseAnalysisAreasOnMap:a.reverseAnalysisAreasOnMap,attachmentsStore:P,geClient:q.getClient(),templateVariableProvider:Q,customLogo:a.customLogo,config:{portalUrl:a.portalUrl,geoenrichmentUrl:a.geoenrichmentUrl,geometryServiceUrl:a.geometryServiceUrl,printMapTaskUrl:a.printMapTaskUrl,countryID:a.countryID,hierarchy:a.hierarchy,reportID:a.reportID,variables:a.variables}};return n(t.applyRunReportAndGetDataResults(R,B),function(){f(1);return B})})})})},_discoverPortal:function(b){return O.getPortalSelf(b.portalUrl).then(function(e){b.geoenrichmentUrl=
b.geoenrichmentUrl||e.helperServices.geoenrichment.url;var d=D.id.findCredential(b.portalUrl);q.setGeoenrichmentUrl(b.geoenrichmentUrl,d&&d.token);b.geometryServiceUrl=b.geometryServiceUrl||e.helperServices.geometry.url;N.setGeometryServiceUrl(b.geometryServiceUrl);b.printMapTaskUrl=b.printMapTaskUrl||e.helperServices.printTask.url;K.setPrintMapTaskUrl(b.printMapTaskUrl)})},reportDataToSingleAreaReportData:function(b,e){var d=e.currentFeatureIndex||0,f=m.mixin({},b.fieldData);f.areaData=[f.areaData[d]];
var a=[m.mixin({},b.analysisAreas[d])];x.removeGroupInfo(a);var c=b.attachmentsStore;return{isMultiFeature:!1,reportTitle:e.reportTitle,templateJson:e.templateJson,reportObject:b.reportObject,fieldData:f,analysisAreas:a,combinedAreasInfo:null,reverseAnalysisAreasOnMap:!1,attachmentsStore:c&&{getImages:function(){c.supportsMultipleAreas&&c.setCurrentAnalysisAreaIndex(d);return c.getImages()},getAttributes:function(){c.supportsMultipleAreas&&c.setCurrentAnalysisAreaIndex(d);return c.getAttributes()},
getNotes:function(){c.supportsMultipleAreas&&c.setCurrentAnalysisAreaIndex(d);return c.getNotes()}},geClient:b.geClient,templateVariableProvider:b.templateVariableProvider,config:b.config}},_getCurrentContext:function(){return this._currentContext},_onCreateReportStarted:function(){}})});