// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),function(t,r,n,v,u,x,A,y,p,f,k,h,d,q,g,m,l,z,B,J,K,L,C){function G(a){return function(b){y[b?
"set":"remove"](this.domNode,a,b);this._set(a,b)}}d.add("dijit-legacy-requires",!q.isAsync);d.add("dojo-bidi",!1);d("dijit-legacy-requires")&&l(0,function(){t(["dijit/_base/manager"])});var H={};v=x("dijit._WidgetBase",[z,K],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:G("lang"),dir:"",_setDirAttr:G("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(a){this._set("ownerDocument",
a)},attributeMap:{},_blankGif:v.blankGif||t.toUrl("dojo/resources/blank.gif"),textDir:"",_introspect:function(){var a=this.constructor;if(!a._setterAttrs){var b=a.prototype,c=a._setterAttrs=[];a=a._onMap={};for(var e in b.attributeMap)c.push(e);for(e in b)/^on/.test(e)&&(a[e.substring(2).toLowerCase()]=e),/^_set[A-Z](.*)Attr$/.test(e)&&(e=e.charAt(4).toLowerCase()+e.substr(5,e.length-9),b.attributeMap&&e in b.attributeMap||c.push(e))}},postscript:function(a,b){this.create(a,b)},create:function(a,
b){this._introspect();this.srcNodeRef=A.byId(b);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&this.srcNodeRef.id&&"string"==typeof this.srcNodeRef.id&&(this.id=this.srcNodeRef.id);a&&(this.params=a,g.mixin(this,a));this.postMixInProperties();this.id||(this.id=C.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=J.body(this.ownerDocument);
C.add(this);this.buildRendering();if(this.domNode){this._applyAttributes();if((a=this.srcNodeRef)&&a.parentNode&&this.domNode!==a){a.parentNode.replaceChild(this.domNode,a);var c=!0}this.domNode.setAttribute("widgetId",this.id)}this.postCreate();c&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a={},b;for(b in this.params||{})a[b]=this._get(b);r.forEach(this.constructor._setterAttrs,function(c){if(!(c in a)){var e=this._get(c);e&&this.set(c,e)}},this);for(b in a)this.set(b,
a[b])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(r.map(a,function(b){return b+"Rtl"})));p.add(this.domNode,a)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,r.forEach(this.getChildren(),function(a){a._started||a._destroyed||!g.isFunction(a.startup)||(a.startup(),a._started=!0)}))},
destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},destroy:function(a){function b(c){c.destroyRecursive?c.destroyRecursive(a):c.destroy&&c.destroy(a)}this._beingDestroyed=!0;this.uninitialize();r.forEach(this._connects,g.hitch(this,"disconnect"));r.forEach(this._supportingWidgets,b);this.domNode&&r.forEach(C.findWidgets(this.domNode,this.containerNode),b);this.destroyRendering(a);C.remove(this.id);this._destroyed=!0},destroyRendering:function(a){this.bgIframe&&
(this.bgIframe.destroy(a),delete this.bgIframe);this.domNode&&(a?y.remove(this.domNode,"widgetId"):f.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(a||f.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){r.forEach(this.getChildren(),function(b){b.destroyRecursive&&b.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(a){var b=this.domNode;g.isObject(a)?h.set(b,a):b.style.cssText=b.style.cssText?b.style.cssText+("; "+a):a;this._set("style",
a)},_attrToDom:function(a,b,c){c=3<=arguments.length?c:this.attributeMap[a];r.forEach(g.isArray(c)?c:[c],function(e){var w=this[e.node||e||"domNode"];switch(e.type||"attribute"){case "attribute":g.isFunction(b)&&(b=g.hitch(this,b));e=e.attribute?e.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;w.tagName?y.set(w,e,b):w.set(e,b);break;case "innerText":w.innerHTML="";w.appendChild(this.ownerDocument.createTextNode(b));break;case "textContent":w.textContent=b;break;case "innerHTML":w.innerHTML=
b;break;case "class":p.replace(w,b,this[a]);break;case "toggleClass":p.toggle(w,e.className||a,b)}},this)},get:function(a){var b=this._getAttrNames(a);return this[b.g]?this[b.g]():this._get(a)},set:function(a,b){if("object"===typeof a){for(var c in a)this.set(c,a[c]);return this}c=this._getAttrNames(a);var e=this[c.s];if(g.isFunction(e))var w=e.apply(this,Array.prototype.slice.call(arguments,1));else{e=this.focusNode&&!g.isFunction(this.focusNode)?"focusNode":"domNode";var F=this[e]&&this[e].tagName,
D;if((D=F)&&!(D=H[F])){D=this[e];var I={};for(E in D)I[E.toLowerCase()]=!0;D=H[F]=I}var E=D;c=a in this.attributeMap?this.attributeMap[a]:c.s in this?this[c.s]:E&&c.l in E&&"function"!=typeof b||/^aria-|^data-|^role$/.test(a)?e:null;null!=c&&this._attrToDom(a,b,c);this._set(a,b)}return w||this},_attrPairNames:{},_getAttrNames:function(a){var b=this._attrPairNames;if(b[a])return b[a];var c=a.replace(/^[a-z]|-[a-zA-Z]/g,function(e){return e.charAt(e.length-1).toUpperCase()});return b[a]={n:a+"Node",
s:"_set"+c+"Attr",g:"_get"+c+"Attr",l:c.toLowerCase()}},_set:function(a,b){var c=this[a];this[a]=b;!this._created||c===b||c!==c&&b!==b||(this._watchCallbacks&&this._watchCallbacks(a,c,b),this.emit("attrmodified-"+a,{detail:{prevValue:c,newValue:b}}))},_get:function(a){return this[a]},emit:function(a,b,c){b=b||{};void 0===b.bubbles&&(b.bubbles=!0);void 0===b.cancelable&&(b.cancelable=!0);b.detail||(b.detail={});b.detail.widget=this;var e,w=this["on"+a];w&&(e=w.apply(this,c?c:[b]));this._started&&!this._beingDestroyed&&
m.emit(this.domNode,a.toLowerCase(),b);return e},on:function(a,b){var c=this._onMap(a);return c?n.after(this,c,b,!0):this.own(m(this.domNode,a,b))[0]},_onMap:function(a){var b=this.constructor,c=b._onMap;if(!c){c=b._onMap={};for(var e in b.prototype)/^on/.test(e)&&(c[e.replace(/^on/,"").toLowerCase()]=e)}return c["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?C.findWidgets(this.containerNode):
[]},getParent:function(){return C.getEnclosingWidget(this.domNode.parentNode)},connect:function(a,b,c){return this.own(u.connect(a,b,this,c))[0]},disconnect:function(a){a.remove()},subscribe:function(a,b){return this.own(B.subscribe(a,g.hitch(this,b)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():k.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=h.get(this.domNode,"display")},placeAt:function(a,b){var c=
!a.tagName&&C.byId(a);!c||!c.addChild||b&&"number"!==typeof b?(a=c&&"domNode"in c?c.containerNode&&!/after|before|replace/.test(b||"")?c.containerNode:c.domNode:A.byId(a,this.ownerDocument),f.place(this.domNode,a,b),!this._started&&(this.getParent()||{})._started&&this.startup()):c.addChild(this,b);return this},defer:function(a,b){var c=setTimeout(g.hitch(this,function(){c&&(c=null,this._destroyed||g.hitch(this,a)())}),b||0);return{remove:function(){c&&(clearTimeout(c),c=null);return null}}}});d("dojo-bidi")&&
v.extend(L);return v})},"dijit/Destroyable":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(t,r,n){return n("dijit.Destroyable",null,{destroy:function(v){this._destroyed=!0},own:function(){var v=["destroyRecursive","destroy","remove"];t.forEach(arguments,function(u){function x(){A.remove();t.forEach(y,function(f){f.remove()})}var A=r.before(this,"destroy",function(f){u[p](f)}),y=[];if(u.then){var p="cancel";u.then(x,x)}else t.forEach(v,function(f){"function"===typeof u[f]&&
(p||(p=f),y.push(r.after(u,f,x,!0)))})},this);return arguments}})})},"dijit/_TemplatedMixin":function(){define("dojo/cache dojo/_base/declare dojo/dom-construct dojo/_base/lang dojo/on dojo/sniff dojo/string ./_AttachMixin".split(" "),function(t,r,n,v,u,x,A,y){var p=r("dijit._TemplatedMixin",y,{templateString:null,templatePath:null,_skipNodeCache:!1,searchContainerNode:!0,_stringRepl:function(f){var k=this.declaredClass,h=this;return A.substitute(f,this,function(d,q){"!"==q.charAt(0)&&(d=v.getObject(q.substr(1),
!1,h));if("undefined"==typeof d)throw Error(k+" template:"+q);return null==d?"":"!"==q.charAt(0)?d:this._escapeValue(""+d)},this)},_escapeValue:function(f){return f.replace(/["'<>&]/g,function(k){return{"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;"}[k]})},buildRendering:function(){if(!this._rendered){this.templateString||(this.templateString=t(this.templatePath,{sanitize:!0}));var f=p.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument);
if(v.isString(f)){var k=n.toDom(this._stringRepl(f),this.ownerDocument);if(1!=k.nodeType)throw Error("Invalid template: "+f);}else k=f.cloneNode(!0);this.domNode=k}this.inherited(arguments);this._rendered||this._fillContent(this.srcNodeRef);this._rendered=!0},_fillContent:function(f){var k=this.containerNode;if(f&&k)for(;f.hasChildNodes();)k.appendChild(f.firstChild)}});p._templateCache={};p.getCachedTemplate=function(f,k,h){var d=p._templateCache,q=f,g=d[q];if(g){try{if(!g.ownerDocument||g.ownerDocument==
(h||document))return g}catch(m){}n.destroy(g)}f=A.trim(f);if(k||f.match(/\$\{([^\}]+)\}/g))return d[q]=f;k=n.toDom(f,h);if(1!=k.nodeType)throw Error("Invalid template: "+f);return d[q]=k};x("ie")&&u(window,"unload",function(){var f=p._templateCache,k;for(k in f){var h=f[k];"object"==typeof h&&n.destroy(h);delete f[k]}});return p})},"dojo/cache":function(){define(["./_base/kernel","./text"],function(t){return t.cache})},"dijit/_AttachMixin":function(){define("require dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/mouse dojo/on dojo/touch ./_WidgetBase".split(" "),
function(t,r,n,v,u,x,A,y,p){var f=u.delegate(y,{mouseenter:x.enter,mouseleave:x.leave,keypress:n._keypress}),k;n=v("dijit._AttachMixin",null,{constructor:function(){this._attachPoints=[];this._attachEvents=[]},buildRendering:function(){this.inherited(arguments);this._attachTemplateNodes(this.domNode);this._beforeFillContent()},_beforeFillContent:function(){},_attachTemplateNodes:function(h){for(var d=h;;)if(1==d.nodeType&&(this._processTemplateNode(d,function(q,g){return q.getAttribute(g)},this._attach)||
this.searchContainerNode)&&d.firstChild)d=d.firstChild;else{if(d==h)break;for(;!d.nextSibling;)if(d=d.parentNode,d==h)return;d=d.nextSibling}},_processTemplateNode:function(h,d,q){var g=!0,m=this.attachScope||this,l=d(h,"dojoAttachPoint")||d(h,"data-dojo-attach-point");if(l)for(var z=l.split(/\s*,\s*/);l=z.shift();)u.isArray(m[l])?m[l].push(h):m[l]=h,g="containerNode"!=l,this._attachPoints.push(l);if(d=d(h,"dojoAttachEvent")||d(h,"data-dojo-attach-event"))for(l=d.split(/\s*,\s*/),z=u.trim;d=l.shift();)if(d){var B=
null;-1!=d.indexOf(":")?(B=d.split(":"),d=z(B[0]),B=z(B[1])):d=z(d);B||(B=d);this._attachEvents.push(q(h,d,u.hitch(m,B)))}return g},_attach:function(h,d,q){d=d.replace(/^on/,"").toLowerCase();d="dijitclick"==d?k||(k=t("./a11yclick")):f[d]||d;return A(h,d,q)},_detachTemplateNodes:function(){var h=this.attachScope||this;r.forEach(this._attachPoints,function(d){delete h[d]});this._attachPoints=[];r.forEach(this._attachEvents,function(d){d.remove()});this._attachEvents=[]},destroyRendering:function(){this._detachTemplateNodes();
this.inherited(arguments)}});u.extend(p,{dojoAttachEvent:"",dojoAttachPoint:""});return n})},"url:esri/dijit/templates/HomeButton.html":'\x3cdiv class\x3d"${theme}" role\x3d"presentation"\x3e\r\n    \x3cdiv class\x3d"${_css.container}"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"_homeNode" title\x3d"${_i18n.widgets.homeButton.home.title}" role\x3d"button" class\x3d"${_css.home}" tabindex\x3d"0"\x3e\x3cspan\x3e${_i18n.widgets.homeButton.home.button}\x3c/span\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e',
"*noref":1}});
define("esri/dijit/HomeButton","dojo/Evented dojo/_base/declare dojo/_base/lang dojo/has ../kernel dijit/_WidgetBase dijit/a11yclick dijit/_TemplatedMixin dojo/on dojo/Deferred dojo/text!./templates/HomeButton.html dojo/i18n!../nls/jsapi dojo/dom-class dojo/dom-style".split(" "),function(t,r,n,v,u,x,A,y,p,f,k,h,d,q){t=r("esri.dijit.HomeButton",[x,y,t],{templateString:k,options:{theme:"HomeButton",map:null,extent:null,fit:!1,visible:!0},constructor:function(g,m){g=n.mixin({},this.options,g);this.domNode=
m;this._i18n=h;this.set("map",g.map);this.set("theme",g.theme);this.set("visible",g.visible);this.set("extent",g.extent);this.set("fit",g.fit);this.watch("theme",this._updateThemeWatch);this.watch("visible",this._visible);this._css={container:"homeContainer",home:"home",loading:"loading"}},postCreate:function(){this.inherited(arguments);this.own(p(this._homeNode,A,n.hitch(this,this.home)))},startup:function(){this.inherited(arguments);this.map||(this.destroy(),console.log("HomeButton::map required"));
if(this.map.loaded)this._init();else p.once(this.map,"load",n.hitch(this,function(){this._init()}))},destroy:function(){this.inherited(arguments)},home:function(){var g=new f,m=this.get("extent");this._showLoading();var l={extent:m};m?this.map.extent!==m?this.map.setExtent(m,this.get("fit")).then(n.hitch(this,function(){this._hideLoading();this.emit("home",l);g.resolve(l)}),n.hitch(this,function(z){z||(z=Error("HomeButton::Error setting map extent"));l.error=z;this.emit("home",l);g.reject(z)})):(this._hideLoading(),
this.emit("home",l),g.resolve(l)):(this._hideLoading(),m=Error("HomeButton::home extent is undefined"),l.error=m,this.emit("home",l),g.reject(m));return g.promise},show:function(){this.set("visible",!0)},hide:function(){this.set("visible",!1)},_init:function(){this._visible();this.get("extent")||this.set("extent",this.map.extent);this.set("loaded",!0);this.emit("load",{})},_showLoading:function(){d.add(this._homeNode,this._css.loading)},_hideLoading:function(){d.remove(this._homeNode,this._css.loading)},
_updateThemeWatch:function(g,m,l){d.remove(this.domNode,m);d.add(this.domNode,l)},_visible:function(){this.get("visible")?q.set(this.domNode,"display","block"):q.set(this.domNode,"display","none")}});v("extend-esri")&&n.setObject("dijit.HomeButton",t,u);return t});