// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/map","require dojo/_base/kernel dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/_base/array dojo/_base/event dojo/on dojo/aspect dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dijit/a11yclick dijit/registry ./kernel ./config ./sniff ./lang ./_coremap ./MapNavigationManager dojo/i18n!./nls/jsapi".split(" "),function(z,u,N,C,p,q,D,E,O,F,G,h,v,P,Q,w,R,x,S,k,t,T,U,H){var A={up:"panUp",right:"panRight",down:"panDown",left:"panLeft"},I=
{upperRight:"panUpperRight",lowerRight:"panLowerRight",lowerLeft:"panLowerLeft",upperLeft:"panUpperLeft"},l=C.connect,J=C.disconnect,m=v.create,n=Q.set,K=p.hitch,y=P.getMarginBox,L=u.deprecated,B=p.mixin,M=0;u=N(T,{declaredClass:"esri.Map",constructor:function(a,b){b=b||{};B(this,{_slider:null,_navDiv:null,_mapParams:B({attributionWidth:.45,slider:!0,nav:!1,logo:!0,sliderStyle:"small",sliderPosition:"top-left",sliderOrientation:"vertical",autoResize:!0},b)});B(this,{isMapNavigation:null!=b.isMapNavigation?
b.isMapNavigation:!0,isDoubleClickZoom:null!=b.isDoubleClickZoom?b.isDoubleClickZoom:!0,isClickRecenter:null!=b.isClickRecenter?b.isClickRecenter:!0,isPan:null!=b.isPan?b.isPan:!0,isRubberBandZoom:null!=b.isRubberBandZoom?b.isRubberBandZoom:!0,isPinchZoom:null!=b.isPinchZoom?b.isPinchZoom:!0,isKeyboardNavigation:null!=b.isKeyboardNavigation?b.isKeyboardNavigation:!0,isScrollWheel:null!=b.isScrollWheel?b.isScrollWheel:!0,isShiftDoubleClickZoom:!1,isScrollWheelZoom:!1,isPanArrows:!1,isZoomSlider:!1});
p.isFunction(x._css)&&(x._css=x._css(this._mapParams.force3DTransforms),this.force3DTransforms=this._mapParams.force3DTransforms);a=k("esri-transforms")&&k("esri-transitions");this.navigationMode=this._mapParams.navigationMode||a&&"css-transforms"||"classic";"css-transforms"!==this.navigationMode||a||(this.navigationMode="classic");this.fadeOnZoom=t.isDefined(this._mapParams.fadeOnZoom)?this._mapParams.fadeOnZoom:"css-transforms"===this.navigationMode;"css-transforms"!==this.navigationMode&&(this.fadeOnZoom=
!1);this.setMapCursor("default");this.smartNavigation=b&&b.smartNavigation;if(!(t.isDefined(this.smartNavigation)||!k("mac")||k("esri-touch")||k("esri-pointer")||3.5>=k("ff"))){var c=navigator.userAgent.match(/Mac\s+OS\s+X\s+([\d]+)(\.|_)([\d]+)\D/i);c&&t.isDefined(c[1])&&t.isDefined(c[3])&&(a=parseInt(c[1],10),c=parseInt(c[3],10),this.smartNavigation=10<a||10===a&&6<=c)}a=!0;a=!1;this.showAttribution=t.isDefined(this._mapParams.showAttribution)?this._mapParams.showAttribution:a;this._onLoadHandler_connect=
l(this,"onLoad",this,"_onLoadInitNavsHandler");var d=m("div",{class:"esriControlsBR"+(this._mapParams.nav?" withPanArrows":"")},this.root);if(this.showAttribution)if(a=p.getObject("esri.dijit.Attribution",!1))this._initAttribution(a,d);else{var e=M++,f=this;this._rids&&this._rids.push(e);z(["./dijit/Attribution"],function(g){var r=f._rids?q.indexOf(f._rids,e):-1;-1!==r&&(f._rids.splice(r,1),f._initAttribution(g,d))})}this._mapParams.logo&&(a={},6===k("ie")&&(a.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled\x3d'true', sizingMethod\x3d'crop', src\x3d'"+
z.toUrl("./images/map/logo-med.png")+"')"),this._ogol=m("div",{style:a,tabIndex:"0",title:"Esri"},d),this._setLogoSize(),this._onMapResizeLogo_connect=l(this,"onResize",this,"_setLogoSize"),this._ogol_connect=l(this._ogol,w,this,"_openLogoLink"));this.navigationManager=new U(this);b&&b.basemap&&(this._onLoadFix=!0,this.setBasemap(b.basemap),this._onLoadFix=!1);if(this.autoResize=this._mapParams.autoResize)b=this._getEnclosingResizableWidget(this.container)||window,a=this.resize,this._rszSignal=E.pausable(b,
"resize",a),this._oriSignal=E.pausable(window,"orientationchange",a),O.after(b,"resize",a,!0),this._startResizeTimer()},_startResizeTimer:function(){clearTimeout(this._persistentTimer);this._persistentTimer=setTimeout(this._timedResize,2*this.resizeDelay)},_getEnclosingResizableWidget:function(a){var b=R.getEnclosingWidget(a);return b?b.resize?b:this._getEnclosingResizableWidget(a.parentNode):b},_setLogoSize:function(){this._ogol&&(25E4>this.root.clientWidth*this.root.clientHeight?(h.remove(this._ogol,
"logo-med"),h.add(this._ogol,"logo-sm")):(h.remove(this._ogol,"logo-sm"),h.add(this._ogol,"logo-med")))},_initAttribution:function(a,b){b=m("span",{class:"esriAttribution"},b,"first");n(b,"maxWidth",Math.floor(this.width*this._mapParams.attributionWidth)+"px");this._connects.push(l(b,w,function(){h.contains(this,"esriAttributionOpen")?h.remove(this,"esriAttributionOpen"):this.scrollWidth>this.clientWidth&&h.add(this,"esriAttributionOpen")}));this.attribution=new a({map:this},b)},_cleanUp:function(){this.disableMapNavigation();
this.navigationManager.destroy();var a=this._slider;a&&a.destroy&&!a._destroyed&&a.destroy();a=this._navDiv;var b=this.attribution;a&&v.destroy(a);b&&b.destroy();this._connects.push(this._slider_connect,this._ogol_connect,this._rszSignal,this._oriSignal);q.forEach(this._connects,J);clearInterval(this._persistentTimer);this.attribution=this.navigationManager=this._rids=this._connects=this._slider_connect=this._ogol_connect=this._rszSignal=this._oriSignal=this._persistentTimer=null;this.inherited("_cleanUp",
arguments)},_isPanningOrZooming:function(){return this.__panning||this.__zooming},_canZoom:function(a){var b=this.getLevel();return!this.__tileInfo||!(b===this.getMinZoom()&&0>a||b===this.getMaxZoom()&&0<a)},_onLoadInitNavsHandler:function(){this._evalMapNavigation();this._createNav();if("small"===this._mapParams.sliderStyle||!this._createSlider)this._createSimpleSlider();else if(this._mapParams.slider){var a=-1!==this._getSliderClass(!0).indexOf("Horizontal");a=[a?"dijit.form.HorizontalSlider":"dijit.form.VerticalSlider",
a?"dijit.form.HorizontalRule":"dijit.form.VerticalRule",a?"dijit.form.HorizontalRuleLabels":"dijit.form.VerticalRuleLabels"];if(q.some(a,function(d){return!p.getObject(d,!1)})){a=q.map(a,function(d){return d.replace(/\./g,"/")});var b=M++,c=this;this._rids&&this._rids.push(b);z(a,function(){var d=c._rids?q.indexOf(c._rids,b):-1;-1!==d&&(c._rids.splice(d,1),c._createSlider.apply(c,arguments))})}else a=q.map(a,function(d){return p.getObject(d,!1)}),this._createSlider.apply(this,a)}J(this._onLoadHandler_connect)},
_createNav:function(){if(this._mapParams.nav){var a,b=h.add,c=this.id;this._navDiv=m("div",{id:c+"_navdiv"},this.root);b(this._navDiv,"navDiv");var d=this.width/2,e=this.height/2;for(a in A){var f=A[a];var g=m("div",{id:c+"_pan_"+a},this._navDiv);b(g,"fixedPan "+f);if("up"===a||"down"===a){var r=parseInt(y(g).w,10)/2;n(g,{left:d-r+"px",zIndex:30})}else r=parseInt(y(g).h,10)/2,n(g,{top:e-r+"px",zIndex:30});this._connects.push(l(g,"onclick",K(this,this[f])))}this._onMapResizeNavHandler_connect=l(this,
"onResize",this,"_onMapResizeNavHandler");for(a in I)f=I[a],g=m("div",{id:c+"_pan_"+a,style:{zIndex:30}},this._navDiv),b(g,"fixedPan "+f),this._connects.push(l(g,"onclick",K(this,this[f])));this.isPanArrows=!0}},_onMapResizeNavHandler:function(a,b,c){a=this.id;b/=2;c/=2;var d=F.byId,e;for(e in A){var f=d(a+"_pan_"+e);if("up"===e||"down"===e){var g=parseInt(y(f).w,10)/2;n(f,"left",b-g+"px")}else g=parseInt(y(f).h,10)/2,n(f,"top",c-g+"px")}},_createSimpleSlider:function(){if(this._mapParams.slider){var a=
this._slider=m("div",{id:this.id+"_zoom_slider",class:this._getSliderClass(),style:{zIndex:30}}),b=m("div",{class:"esriSimpleSliderIncrementButton",tabIndex:"0",role:"button"},a),c=m("div",{class:"esriSimpleSliderDecrementButton",tabIndex:"0",role:"button"},a);this._addZoomButtonTooltips(b,c);this._incButton=b;this._decButton=c;this._simpleSliderZoomHandler(null,null,null,this.getLevel());var d=H.widgets.zoomSlider;this._addZoomButtonIcon(b,"+",d.zoomIn);this._addZoomButtonIcon(c,"\x26minus;",d.zoomOut);
8>k("ie")&&h.add(c,"dj_ie67Fix");this._connects.push(l(b,w,this,this._simpleSliderChangeHandler));this._connects.push(l(c,w,this,this._simpleSliderChangeHandler));(-1<this.getMaxZoom()||-1<this.getMinZoom())&&this._connects.push(l(this,"onZoomEnd",this,this._simpleSliderZoomHandler));10>k("ie")&&F.setSelectable(a,!1);this.root.appendChild(a);this.isZoomSlider=!0}},_simpleSliderChangeHandler:function(a){D.stop(a);a=-1!==a.currentTarget.className.indexOf("IncrementButton")?!0:!1;this._extentUtil({numLevels:a?
1:-1})},_simpleSliderZoomHandler:function(a,b,c,d){var e;a=this._incButton;b=this._decButton;-1<d&&d===this.getMaxZoom()?e=a:-1<d&&d===this.getMinZoom()&&(e=b);e?(h.add(e,"esriSimpleSliderDisabledButton"),h.remove(e===a?b:a,"esriSimpleSliderDisabledButton")):(h.remove(a,"esriSimpleSliderDisabledButton"),h.remove(b,"esriSimpleSliderDisabledButton"))},_getSliderClass:function(a){a=a?"Large":"Simple";var b=this._mapParams.sliderOrientation,c=this._mapParams.sliderPosition||"";b=b&&"horizontal"===b.toLowerCase()?
"esri"+a+"SliderHorizontal":"esri"+a+"SliderVertical";if(c)switch(c.toLowerCase()){case "top-left":c="esri"+a+"SliderTL";break;case "top-right":c="esri"+a+"SliderTR";break;case "bottom-left":c="esri"+a+"SliderBL";break;case "bottom-right":c="esri"+a+"SliderBR"}return"esri"+a+"Slider "+b+" "+c},_addZoomButtonIcon:function(a,b,c){v.create("span",{"aria-hidden":"true",role:"presentation",innerHTML:b},a);v.create("span",{class:"esriIconFallbackText",innerHTML:c},a)},_addZoomButtonTooltips:function(a,
b){var c=H.widgets.zoomSlider;G.set(a,"title",c.zoomIn);G.set(b,"title",c.zoomOut)},_openLogoLink:function(a){window.open(S.defaults.map.logoLink,"_blank");D.stop(a)},enableMapNavigation:function(){this.isMapNavigation||(this.isMapNavigation=!0,this._evalMapNavigation())},disableMapNavigation:function(){this.isMapNavigation&&(this.isMapNavigation=!1,this._evalMapNavigation())},_evalMapNavigation:function(){this.isMapNavigation?this.navigationManager.enableNavigation():this.navigationManager.disableNavigation()},
_evalNavigationFeature:function(a){if(this.isMapNavigation&&this["is"+a])this.navigationManager["enable"+a]();else this.navigationManager["disable"+a]()},enableDoubleClickZoom:function(){this.isDoubleClickZoom||(this.isDoubleClickZoom=!0,this._evalNavigationFeature("DoubleClickZoom"))},disableDoubleClickZoom:function(){this.isDoubleClickZoom&&(this.isDoubleClickZoom=!1,this._evalNavigationFeature("DoubleClickZoom"))},enableShiftDoubleClickZoom:function(){this.isShiftDoubleClickZoom||(L(this.declaredClass+
": Map.(enable/disable)ShiftDoubleClickZoom deprecated. Shift-Double-Click zoom behavior will not be supported.",null,"v2.0"),this.navigationManager.enableShiftDoubleClickZoom(),this.isShiftDoubleClickZoom=!0)},disableShiftDoubleClickZoom:function(){this.isShiftDoubleClickZoom&&(L(this.declaredClass+": Map.(enable/disable)ShiftDoubleClickZoom deprecated. Shift-Double-Click zoom behavior will not be supported.",null,"v2.0"),this.navigationManager.disableShiftDoubleClickZoom(),this.isShiftDoubleClickZoom=
!1)},enableClickRecenter:function(){this.isClickRecenter||(this.isClickRecenter=!0,this._evalNavigationFeature("ClickRecenter"))},disableClickRecenter:function(){this.isClickRecenter&&(this.isClickRecenter=!1,this._evalNavigationFeature("ClickRecenter"))},enablePan:function(){this.isPan||(this.isPan=!0,this._evalNavigationFeature("Pan"))},disablePan:function(){this.isPan&&(this.isPan=!1,this._evalNavigationFeature("Pan"))},enableRubberBandZoom:function(){this.isRubberBandZoom||(this.isRubberBandZoom=
!0,this._evalNavigationFeature("RubberBandZoom"))},disableRubberBandZoom:function(){this.isRubberBandZoom&&(this.isRubberBandZoom=!1,this._evalNavigationFeature("RubberBandZoom"))},enablePinchZoom:function(){this.isPinchZoom||(this.isPinchZoom=!0,this._evalNavigationFeature("PinchZoom"))},disablePinchZoom:function(){this.isPinchZoom&&(this.isPinchZoom=!1,this._evalNavigationFeature("PinchZoom"))},enableKeyboardNavigation:function(){this.isKeyboardNavigation||(this.isKeyboardNavigation=!0,this._evalNavigationFeature("KeyboardNavigation"))},
disableKeyboardNavigation:function(){this.isKeyboardNavigation&&(this.isKeyboardNavigation=!1,this._evalNavigationFeature("KeyboardNavigation"))},enableScrollWheel:function(){this.isScrollWheel||(this.isScrollWheel=!0,this._evalNavigationFeature("ScrollWheel"))},disableScrollWheel:function(){this.isScrollWheel&&(this.isScrollWheel=!1,this._evalNavigationFeature("ScrollWheel"))},enableScrollWheelZoom:function(){this.isScrollWheelZoom||(this.navigationManager.enableScrollWheelZoom(),this.isScrollWheelZoom=
!0)},disableScrollWheelZoom:function(){this.isScrollWheelZoom&&(this.navigationManager.disableScrollWheelZoom(),this.isScrollWheelZoom=!1)},enableScrollWheelPan:function(){this.isScrollWheelPan||this.navigationManager.enableScrollWheelPan()},disableScrollWheelPan:function(){this.isScrollWheelPan&&this.navigationManager.disableScrollWheelPan()},showPanArrows:function(){this._navDiv&&(this._navDiv.style.display="block",this.isPanArrows=!0)},hidePanArrows:function(){this._navDiv&&(this._navDiv.style.display=
"none",this.isPanArrows=!1)},showZoomSlider:function(){this._slider&&(n(this._slider.domNode||this._slider,"visibility","inherit"),this.isZoomSlider=!0)},hideZoomSlider:function(){this._slider&&(n(this._slider.domNode||this._slider,"visibility","hidden"),this.isZoomSlider=!1)},onClick:function(a){a.graphic||(a.graphic=this.syncHitTestForWebGL(a))}});k("extend-esri")&&(x.Map=u);return u});