// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),function(v,q,w,r,u,y,A,z,t,g,k,h,d,n,l,B,e,m,p,J,K,L,C){function G(a){return function(b){z[b?
"set":"remove"](this.domNode,a,b);this._set(a,b)}}d.add("dijit-legacy-requires",!n.isAsync);d.add("dojo-bidi",!1);d("dijit-legacy-requires")&&e(0,function(){v(["dijit/_base/manager"])});var H={};r=y("dijit._WidgetBase",[m,K],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:G("lang"),dir:"",_setDirAttr:G("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(a){this._set("ownerDocument",
a)},attributeMap:{},_blankGif:r.blankGif||v.toUrl("dojo/resources/blank.gif"),textDir:"",_introspect:function(){var a=this.constructor;if(!a._setterAttrs){var b=a.prototype,c=a._setterAttrs=[];a=a._onMap={};for(var f in b.attributeMap)c.push(f);for(f in b)/^on/.test(f)&&(a[f.substring(2).toLowerCase()]=f),/^_set[A-Z](.*)Attr$/.test(f)&&(f=f.charAt(4).toLowerCase()+f.substr(5,f.length-9),b.attributeMap&&f in b.attributeMap||c.push(f))}},postscript:function(a,b){this.create(a,b)},create:function(a,
b){this._introspect();this.srcNodeRef=A.byId(b);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&this.srcNodeRef.id&&"string"==typeof this.srcNodeRef.id&&(this.id=this.srcNodeRef.id);a&&(this.params=a,l.mixin(this,a));this.postMixInProperties();this.id||(this.id=C.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=J.body(this.ownerDocument);
C.add(this);this.buildRendering();if(this.domNode){this._applyAttributes();if((a=this.srcNodeRef)&&a.parentNode&&this.domNode!==a){a.parentNode.replaceChild(this.domNode,a);var c=!0}this.domNode.setAttribute("widgetId",this.id)}this.postCreate();c&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a={},b;for(b in this.params||{})a[b]=this._get(b);q.forEach(this.constructor._setterAttrs,function(c){if(!(c in a)){var f=this._get(c);f&&this.set(c,f)}},this);for(b in a)this.set(b,
a[b])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(q.map(a,function(b){return b+"Rtl"})));t.add(this.domNode,a)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,q.forEach(this.getChildren(),function(a){a._started||a._destroyed||!l.isFunction(a.startup)||(a.startup(),a._started=!0)}))},
destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},destroy:function(a){function b(c){c.destroyRecursive?c.destroyRecursive(a):c.destroy&&c.destroy(a)}this._beingDestroyed=!0;this.uninitialize();q.forEach(this._connects,l.hitch(this,"disconnect"));q.forEach(this._supportingWidgets,b);this.domNode&&q.forEach(C.findWidgets(this.domNode,this.containerNode),b);this.destroyRendering(a);C.remove(this.id);this._destroyed=!0},destroyRendering:function(a){this.bgIframe&&
(this.bgIframe.destroy(a),delete this.bgIframe);this.domNode&&(a?z.remove(this.domNode,"widgetId"):g.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(a||g.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){q.forEach(this.getChildren(),function(b){b.destroyRecursive&&b.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(a){var b=this.domNode;l.isObject(a)?h.set(b,a):b.style.cssText=b.style.cssText?b.style.cssText+("; "+a):a;this._set("style",
a)},_attrToDom:function(a,b,c){c=3<=arguments.length?c:this.attributeMap[a];q.forEach(l.isArray(c)?c:[c],function(f){var x=this[f.node||f||"domNode"];switch(f.type||"attribute"){case "attribute":l.isFunction(b)&&(b=l.hitch(this,b));f=f.attribute?f.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;x.tagName?z.set(x,f,b):x.set(f,b);break;case "innerText":x.innerHTML="";x.appendChild(this.ownerDocument.createTextNode(b));break;case "textContent":x.textContent=b;break;case "innerHTML":x.innerHTML=
b;break;case "class":t.replace(x,b,this[a]);break;case "toggleClass":t.toggle(x,f.className||a,b)}},this)},get:function(a){var b=this._getAttrNames(a);return this[b.g]?this[b.g]():this._get(a)},set:function(a,b){if("object"===typeof a){for(var c in a)this.set(c,a[c]);return this}c=this._getAttrNames(a);var f=this[c.s];if(l.isFunction(f))var x=f.apply(this,Array.prototype.slice.call(arguments,1));else{f=this.focusNode&&!l.isFunction(this.focusNode)?"focusNode":"domNode";var F=this[f]&&this[f].tagName,
D;if((D=F)&&!(D=H[F])){D=this[f];var I={};for(E in D)I[E.toLowerCase()]=!0;D=H[F]=I}var E=D;c=a in this.attributeMap?this.attributeMap[a]:c.s in this?this[c.s]:E&&c.l in E&&"function"!=typeof b||/^aria-|^data-|^role$/.test(a)?f:null;null!=c&&this._attrToDom(a,b,c);this._set(a,b)}return x||this},_attrPairNames:{},_getAttrNames:function(a){var b=this._attrPairNames;if(b[a])return b[a];var c=a.replace(/^[a-z]|-[a-zA-Z]/g,function(f){return f.charAt(f.length-1).toUpperCase()});return b[a]={n:a+"Node",
s:"_set"+c+"Attr",g:"_get"+c+"Attr",l:c.toLowerCase()}},_set:function(a,b){var c=this[a];this[a]=b;!this._created||c===b||c!==c&&b!==b||(this._watchCallbacks&&this._watchCallbacks(a,c,b),this.emit("attrmodified-"+a,{detail:{prevValue:c,newValue:b}}))},_get:function(a){return this[a]},emit:function(a,b,c){b=b||{};void 0===b.bubbles&&(b.bubbles=!0);void 0===b.cancelable&&(b.cancelable=!0);b.detail||(b.detail={});b.detail.widget=this;var f,x=this["on"+a];x&&(f=x.apply(this,c?c:[b]));this._started&&!this._beingDestroyed&&
B.emit(this.domNode,a.toLowerCase(),b);return f},on:function(a,b){var c=this._onMap(a);return c?w.after(this,c,b,!0):this.own(B(this.domNode,a,b))[0]},_onMap:function(a){var b=this.constructor,c=b._onMap;if(!c){c=b._onMap={};for(var f in b.prototype)/^on/.test(f)&&(c[f.replace(/^on/,"").toLowerCase()]=f)}return c["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?C.findWidgets(this.containerNode):
[]},getParent:function(){return C.getEnclosingWidget(this.domNode.parentNode)},connect:function(a,b,c){return this.own(u.connect(a,b,this,c))[0]},disconnect:function(a){a.remove()},subscribe:function(a,b){return this.own(p.subscribe(a,l.hitch(this,b)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():k.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=h.get(this.domNode,"display")},placeAt:function(a,b){var c=
!a.tagName&&C.byId(a);!c||!c.addChild||b&&"number"!==typeof b?(a=c&&"domNode"in c?c.containerNode&&!/after|before|replace/.test(b||"")?c.containerNode:c.domNode:A.byId(a,this.ownerDocument),g.place(this.domNode,a,b),!this._started&&(this.getParent()||{})._started&&this.startup()):c.addChild(this,b);return this},defer:function(a,b){var c=setTimeout(l.hitch(this,function(){c&&(c=null,this._destroyed||l.hitch(this,a)())}),b||0);return{remove:function(){c&&(clearTimeout(c),c=null);return null}}}});d("dojo-bidi")&&
r.extend(L);return r})},"dijit/Destroyable":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(v,q,w){return w("dijit.Destroyable",null,{destroy:function(r){this._destroyed=!0},own:function(){var r=["destroyRecursive","destroy","remove"];v.forEach(arguments,function(u){function y(){A.remove();v.forEach(z,function(g){g.remove()})}var A=q.before(this,"destroy",function(g){u[t](g)}),z=[];if(u.then){var t="cancel";u.then(y,y)}else v.forEach(r,function(g){"function"===typeof u[g]&&
(t||(t=g),z.push(q.after(u,g,y,!0)))})},this);return arguments}})})},"dijit/_TemplatedMixin":function(){define("dojo/cache dojo/_base/declare dojo/dom-construct dojo/_base/lang dojo/on dojo/sniff dojo/string ./_AttachMixin".split(" "),function(v,q,w,r,u,y,A,z){var t=q("dijit._TemplatedMixin",z,{templateString:null,templatePath:null,_skipNodeCache:!1,searchContainerNode:!0,_stringRepl:function(g){var k=this.declaredClass,h=this;return A.substitute(g,this,function(d,n){"!"==n.charAt(0)&&(d=r.getObject(n.substr(1),
!1,h));if("undefined"==typeof d)throw Error(k+" template:"+n);return null==d?"":"!"==n.charAt(0)?d:this._escapeValue(""+d)},this)},_escapeValue:function(g){return g.replace(/["'<>&]/g,function(k){return{"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;"}[k]})},buildRendering:function(){if(!this._rendered){this.templateString||(this.templateString=v(this.templatePath,{sanitize:!0}));var g=t.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument);
if(r.isString(g)){var k=w.toDom(this._stringRepl(g),this.ownerDocument);if(1!=k.nodeType)throw Error("Invalid template: "+g);}else k=g.cloneNode(!0);this.domNode=k}this.inherited(arguments);this._rendered||this._fillContent(this.srcNodeRef);this._rendered=!0},_fillContent:function(g){var k=this.containerNode;if(g&&k)for(;g.hasChildNodes();)k.appendChild(g.firstChild)}});t._templateCache={};t.getCachedTemplate=function(g,k,h){var d=t._templateCache,n=g,l=d[n];if(l){try{if(!l.ownerDocument||l.ownerDocument==
(h||document))return l}catch(B){}w.destroy(l)}g=A.trim(g);if(k||g.match(/\$\{([^\}]+)\}/g))return d[n]=g;k=w.toDom(g,h);if(1!=k.nodeType)throw Error("Invalid template: "+g);return d[n]=k};y("ie")&&u(window,"unload",function(){var g=t._templateCache,k;for(k in g){var h=g[k];"object"==typeof h&&w.destroy(h);delete g[k]}});return t})},"dojo/cache":function(){define(["./_base/kernel","./text"],function(v){return v.cache})},"dijit/_AttachMixin":function(){define("require dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/mouse dojo/on dojo/touch ./_WidgetBase".split(" "),
function(v,q,w,r,u,y,A,z,t){var g=u.delegate(z,{mouseenter:y.enter,mouseleave:y.leave,keypress:w._keypress}),k;w=r("dijit._AttachMixin",null,{constructor:function(){this._attachPoints=[];this._attachEvents=[]},buildRendering:function(){this.inherited(arguments);this._attachTemplateNodes(this.domNode);this._beforeFillContent()},_beforeFillContent:function(){},_attachTemplateNodes:function(h){for(var d=h;;)if(1==d.nodeType&&(this._processTemplateNode(d,function(n,l){return n.getAttribute(l)},this._attach)||
this.searchContainerNode)&&d.firstChild)d=d.firstChild;else{if(d==h)break;for(;!d.nextSibling;)if(d=d.parentNode,d==h)return;d=d.nextSibling}},_processTemplateNode:function(h,d,n){var l=!0,B=this.attachScope||this,e=d(h,"dojoAttachPoint")||d(h,"data-dojo-attach-point");if(e)for(var m=e.split(/\s*,\s*/);e=m.shift();)u.isArray(B[e])?B[e].push(h):B[e]=h,l="containerNode"!=e,this._attachPoints.push(e);if(d=d(h,"dojoAttachEvent")||d(h,"data-dojo-attach-event"))for(e=d.split(/\s*,\s*/),m=u.trim;d=e.shift();)if(d){var p=
null;-1!=d.indexOf(":")?(p=d.split(":"),d=m(p[0]),p=m(p[1])):d=m(d);p||(p=d);this._attachEvents.push(n(h,d,u.hitch(B,p)))}return l},_attach:function(h,d,n){d=d.replace(/^on/,"").toLowerCase();d="dijitclick"==d?k||(k=v("./a11yclick")):g[d]||d;return A(h,d,n)},_detachTemplateNodes:function(){var h=this.attachScope||this;q.forEach(this._attachPoints,function(d){delete h[d]});this._attachPoints=[];q.forEach(this._attachEvents,function(d){d.remove()});this._attachEvents=[]},destroyRendering:function(){this._detachTemplateNodes();
this.inherited(arguments)}});u.extend(t,{dojoAttachEvent:"",dojoAttachPoint:""});return w})},"url:esri/dijit/templates/BasemapToggle.html":'\x3cdiv class\x3d"${theme}" role\x3d"presentation" style\x3d"display:none;"\x3e\r\n    \x3cdiv class\x3d"${_css.container}"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"_toggleNode" title\x3d"${_i18n.widgets.basemapToggle.toggle}" role\x3d"button" class\x3d"${_css.toggleButton}" tabindex\x3d"0"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e',"*noref":1}});
define("esri/dijit/BasemapToggle","require dojo/Evented dojo/_base/declare dojo/_base/lang dojo/has ../kernel dijit/_WidgetBase dijit/a11yclick dijit/_TemplatedMixin dojo/on dojo/text!./templates/BasemapToggle.html dojo/i18n!../nls/jsapi dojo/dom-class dojo/dom-style dojo/dom-construct ../basemaps".split(" "),function(v,q,w,r,u,y,A,z,t,g,k,h,d,n,l,B){v=w("esri.dijit.BasemapToggle",[A,t,q],{templateString:k,options:{theme:"BasemapToggle",map:null,visible:!0,basemap:"hybrid",defaultBasemap:"streets",
basemaps:B},constructor:function(e,m){e=r.mixin({},this.options,e);this.domNode=m;this._i18n=h;this.set("map",e.map);this.set("theme",e.theme);this.set("visible",e.visible);this.set("basemaps",e.basemaps);this.set("basemap",e.basemap);this.set("defaultBasemap",e.defaultBasemap);this.watch("theme",this._updateThemeWatch);this.watch("visible",this._visible);this._css={container:"basemapContainer",toggleButton:"toggleButton",basemapImage:"basemapImage",basemapImageContainer:"basemapImageContainer",basemapImageBG:"basemapBG",
basemapTitle:"basemapTitle"}},postCreate:function(){this.inherited(arguments);this.own(g(this._toggleNode,z,r.hitch(this,this.toggle)))},startup:function(){this.inherited(arguments);this.map||(this.destroy(),console.log("BasemapToggle::map required"));if(this.map.loaded)this._init();else g.once(this.map,"load",r.hitch(this,function(){this._init()}))},destroy:function(){this.inherited(arguments)},show:function(){this.set("visible",!0)},hide:function(){this.set("visible",!1)},toggle:function(){var e=
this.map.getBasemap();e&&this.set("defaultBasemap",e);e=this.get("defaultBasemap");var m=this.get("basemap"),p={previousBasemap:e,currentBasemap:m};e!==m?(this.map.setBasemap(m),this.set("basemap",e),this._basemapChange()):p.error=Error("BasemapToggle::Current basemap is same as new basemap");this.emit("toggle",p)},_init:function(){this._visible();this._basemapChange();this.own(g(this.map,"basemap-change",r.hitch(this,function(){this._basemapChange()})));this.set("loaded",!0);this.emit("load",{})},
_getBasemapInfo:function(e){var m=this.get("basemaps");if(m&&m.hasOwnProperty(e))return m[e]},_updateImage:function(){var e=this.get("basemap");e=this._getBasemapInfo(e);var m=e.thumbnailUrl;var p='\x3cdiv class\x3d"'+this._css.basemapImageContainer+'"\x3e';p+='\x3cdiv class\x3d"'+this._css.basemapImage+'"\x3e\x3cdiv class\x3d"'+this._css.basemapImageBG+'" style\x3d"background-image:url('+m+')" title\x3d"'+e.title+'"\x3e\x3c/div\x3e\x3c/div\x3e';p+='\x3cdiv title\x3d"'+e.title+'" class\x3d"'+this._css.basemapTitle+
'"\x3e'+e.title+"\x3c/div\x3e";p+="\x3cdiv\x3e";l.empty(this._toggleNode);l.place(p,this._toggleNode,"only")},_basemapChange:function(){var e=this.map.getBasemap();e&&this.set("defaultBasemap",e);e=this.get("defaultBasemap");var m=this.get("basemap");this._updateImage();d.remove(this._toggleNode,e);d.add(this._toggleNode,m)},_updateThemeWatch:function(e,m,p){this.get("loaded")&&(d.remove(this.domNode,m),d.add(this.domNode,p))},_visible:function(){this.get("visible")?n.set(this.domNode,"display","block"):
n.set(this.domNode,"display","none")}});u("extend-esri")&&r.setObject("dijit.BasemapToggle",v,y);return v});